### PR TITLE
support suggested fixes by analyzing a diff

### LINKED ISSUE #146: no suggested fixes in analyzer report
Hi, I'm creating my own (yes, one more) [linter](https://github.com/sv-tools/gochecker) :) based on the [multichecker](https://pkg.go.dev/golang.org/x/tools/go/analysis/multichecker) and import `gci` as a lib, `pkg/analyzer`.
Everything works fine, the `GCI` provides an error message, but it does not provide the suggested fixes, so the files cannot be formatted automatically :-(

Could you please extend the analyzer to include the fixes as well?

Thank you!

### What version of GCI are you using?

<pre>
v0.9.1
</pre>

### PR DESCRIPTION
**Pull request by SVilgelm**
Added `GetSuggestedFix` function creates unified diff for `unmodifiedFile` and `formattedFile`.
Then analyzes the diff and creates `analysis.SuggestedFix` if needed.

The Analyzer checks the result of `GetSuggestedFix` function and reports as `analysis.Diagnostic`.

Removed the `inspect.Analyzer` dependency since it is not used, but requires extra work

Fix #146

### CODE REVIEW

File: pkg/utils/diff.go [hunk 1]
```diff
@@ -0,0 +1,78 @@
+package utils
```
Comment (daixiang0) [inline pkg/utils/diff.go:1]: Please put under analyzer package and add test for `GetSuggestedFix`.

Comment (SVilgelm) [reply pkg/utils/diff.go:1]: sure

Comment (SVilgelm) [reply pkg/utils/diff.go]: done

File: pkg/analyzer/analyzer.go [hunk 2]
```diff
@@ -44,10 +42,9 @@ func init() {
 }
 
 var Analyzer = &analysis.Analyzer{
-	Name:     "gci",
-	Doc:      "A tool that control golang package import order and make it always deterministic.",
-	Requires: []*analysis.Analyzer{inspect.Analyzer},
```
Comment (daixiang0) [inline pkg/analyzer/analyzer.go:49]: Why remove this?

Comment (SVilgelm) [reply pkg/analyzer/analyzer.go:49]: It is not used by the analyzer at all, but does some work

I tested and did not find any problems

**Review by daixiang0 — APPROVED** [review]
